backend:
  name: github
  repo: lutztalk/blog.lutztalk.com
  branch: main
  base_url: https://blog.lutztalk.com
  site_domain: localhost:4321
  auth_type: pkce
  auth_scope: repo

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/data/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    frontmatter_delimiter: ["---", "---"]
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Author", name: "author", widget: "string", default: "Austin Lutz", required: true }
      - { 
          label: "Publish Date", 
          name: "pubDatetime", 
          widget: "datetime", 
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ss",
          required: true 
        }
      - { 
          label: "Modified Date", 
          name: "modDatetime", 
          widget: "datetime", 
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ss",
          required: false,
          default: null
        }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          default: ["others"],
          field: { label: "Tag", name: "tag", widget: "string" },
          required: false 
        }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }

